spring.application.name=transaction-processing-service

spring.datasource.url=jdbc:postgresql://localhost:5432/tps
spring.datasource.username=tps_user
spring.datasource.password=change_me_locally

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
